Minimal develop mode #1
EmpregoLigado/frontend-code-challenge pull request #1
Opened 2017-04-06 18:30 UTC by nelsera

This PR contains the basic environment for developing the component using React.

2017-04-17 18:51 UTC, LeoVitale requested changes

2017-04-17 18:51 UTC, LeoVitale commented on src/components/Calendar/Calendar.js
> +    this.getHolidays(data).then((res) => {
Remover chamada Ajax do Render(), usar o Ciclo de Vida de um component React (componentDidMout ou componentWillMout)

2017-04-17 18:51 UTC, LeoVitale commented on src/components/Calendar/Calendar.js
> +
Aqui deveria ter a mudança de Estado do componente

2017-04-17 21:08 UTC, nelsera commented on src/components/Calendar/Calendar.js
> +    this.getHolidays(data).then((res) => {
Done!

2017-04-17 21:08 UTC, nelsera reviewed
Done!

2017-04-17 21:21 UTC, nelsera commented on src/components/Calendar/Calendar.js
> +    this.getHolidays(data).then((res) => {
Valeu pela correção Leo! 
Pra fazer os efeitos colaterais, optei pelo componentDidMount mesmo.

2017-04-17 21:21 UTC, nelsera commented on src/components/Calendar/Calendar.js
> +
Tratei o estado.

2017-04-18 19:07 UTC, efreesen approved these changes
Great, nice job!!!

Added some minor tips, but you got the job done!

Congratulations 🎆 🎉 🎊

2017-04-18 19:07 UTC, efreesen commented on src/components/Calendar/Calendar.js
> +      year: `2017`
Some tips here:

- I would move this key to a config file, instead of hardcoding it here;
- You could use a dynamic way to get the year.

2017-04-18 19:07 UTC, efreesen commented on src/modules/helpers.js
> +    	// Error
I would suggest omitting this `catch` block If we are actually not handling the error.

WDYT?

2017-04-18 19:07 UTC, efreesen commented on src/components/Calendar/Calendar.js
> +import 'react-infinite-calendar/styles.css';
Just out of curiosity, is there any reason why you chose this component instead of others?

It really is just a question, no catch here!!! 😝

2017-04-18 19:29 UTC, nelsera commented on src/components/Calendar/Calendar.js
> +import 'react-infinite-calendar/styles.css';
Maybe to avoid same ol same! hahahaha

2017-04-18 19:39 UTC, nelsera commented on src/modules/helpers.js
> +    	// Error
thanks! doing!

2017-04-18 20:06 UTC, nelsera commented on src/components/Calendar/Calendar.js
> +      year: `2017`
Doing!

2017-04-18 20:51 UTC, nelsera commented on src/components/Calendar/Calendar.js
> +      year: `2017`
Done! See when you can.

2017-04-19 14:25 UTC, LeoVitale commented
Great Man! 🎉 🎉 🎉

2017-04-19 14:25 UTC, LeoVitale approved these changes

2017-05-15 14:12 UTC, closed without merging